### ISSUE TITLE
Consider patching a bug till the author of LSP can release new version

### ISSUE THREAD

**Issue by axwnet** [flathub/org.freedesktop.LinuxAudio.Plugins.LSP#12]
There is a bug with Xorg/Xwayland that causes cpu usage to spike to 100% (1 CORE)
there is a patch linked in the Issue below 

https://github.com/sadko4u/lsp-plugins/issues/272

The author can't release a new version anytime soon due to the current circumstances in eastern Europe.

**Comment by hfiguiere** [comment]
1.2.4 is out now.
